---
- name: Install Hyprland Packages
  hosts: localhost
  connection: local
  become: false
  tasks:

    - name: Ensure yay AUR helper is installed
      community.general.pacman:
        name: yay
        state: present
      become: true

    - name: Install official Arch Linux repository packages
      community.general.pacman:
        name:
          - thunar
          - wl-clipboard
          - cliphist
          - xdg-desktop-portal
          - xdg-desktop-portal-hyprland
        state: present
      become: true

    - name: Install AUR packages using yay
      kewlfft.aur.aur:
        name:
          - hyprpolkitagent
          - tofi
        use: yay
        state: present
      become: true
      become_user: aur_builder
