---
- name: Install v3m
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install some apps
      community.general.pacman:
        name: 
          - hyprland
          - alacritty
          - waybar
          - xorg-xwayland
          - qt5-wayland
          - qt6-wayland
        state: present
        update_cache: false
